package Textos

class Texto {

    object t1 {
        const val textoL =
            "La primera mitad del siglo xx asistió al desarrollo gradual de las calculadoras mecánicas que ya habían sido inventadas, sin embargo se hicieron algunas innovaciones importantes.\n" +
                    "\n" +
                    "\n" +
                    "Calculadora mecánica de 1914.\n" +
                    "La máquina sumadora-listadora de Dalton presentada en 1914 fue la primera de su tipo en usar solo diez teclas, convirtiéndose en el primero de muchos modelos diferentes de «sumadoras-listadoras de 10 teclas» fabricadas por diversas compañías.\n" +
                    "\n" +
                    "En 1948 la calculadora miniatura Curta, que se sujeta en una mano para usarse, fue presentada tras su desarrollo por Curt Herzstark en un campo de concentración nazi, suponiendo un desarrollo extremo del mecanismo calculador de ruedas dentadas escalonadas.\n" +
                    "\n" +
                    "\n" +
                    "Una Curta de tipo II, conocida también como “la moledora de pimienta”.\n" +
                    "Desde principios de los años 1900 hasta la década de 1960, las calculadoras mecánicas dominaron el mercado de computación de escritorio (véase Historia del hardware de computador). Los principales fabricantes estadounidenses fueron Friden, Monroe y SCM/Marchant. Estos dispositivos funcionaban con la ayuda de un motor y disponían de carros móviles donde los resultados de los cálculos eran mostrados mediante diales. Casi todos los teclados eran «completos»: cada dígito que podía introducirse tenía su propia columna de nueve teclas (del 1 al 9) más una columna para limpiar, permitiendo la introducción de varios dígitos a la vez. Podría decirse que esto era una entrada paralela, frente a la entrada serie de diez teclas que era común en las sumadoras mecánicas y actualmente es universal en las calculadoras electrónicas. (Casi todas las calculadoras Friden tenían un teclado auxiliar de diez teclas para introducir el multiplicador cuando se realizaba esta operación.) Los teclados completos tenían generalmente diez columnas, si bien algunos modelos de bajo coste tenían solo ocho. La mayoría de las máquinas fabricadas por estas tres compañías no imprimían sus resultados, aunque otras compañías como Olivetti fabricaron calculadoras impresoras.\n" +
                    "\n" +
                    "En esta máquina, las sumas y restas eran realizadas en una sola operación, como en una sumadora convencional, pero la multiplicación y la división se lograban mediante repetidas sumas y restas mecánicas. Friden fabricó una calculadora que también extraía raíces cuadradas, básicamente realizando divisiones, pero con un mecanismo añadido que automáticamente incrementaba el número en el teclado de forma sistemática. Marchant también fabricó un modelo (el SKA) que calculaba raíces cuadradas. Las calculadoras mecánicas de mano, como la ya mencionada Curta de 1945, siguieron usándose hasta que fueron definitivamente desplazadas por las electrónicas a principios de los años 1970. Para 1970 una calculadora podía fabricarse usando solo unos pocos chips de bajo consumo, permitiendo que los modelos portátiles fuesen alimentados con baterías. Las primeras calculadoras electrónicas portátiles aparecieron en Japón en 1970 y pronto fueron comercializadas por todo el mundo. Entre estas estaban la Sanyo ICC-0081 Mini Calculator y la Canon Pocketronic. El avance y aprovechamiento de la calculadora fue en incremento ya que al poder fabricar calculadoras usando unos cuantos chips con un bajo consumo, pudieron surguir las primeras calculadoras portátiles. Sin duda un gran avance para la evolución de la calculadora. En lo que respecta desde 1980-1990 surgió la primera calculadora capaz de realizar cálculos simbólicos que fue la HP-28, lanzada en 1987. Era capaz, por ejemplo, de resolver simbólicamente ecuaciones cuadráticas. La primera calculadora gráfica fue la Casio fx7000G, lanzada en 1985.\n" +
                    "\n" +
                    "\n" +
                    "Facit NTK (1954).\n" +
                    "\n" +
                    "Olivetti Divisumma 24 (1964).\n" +
                    "En Europa fueron comunes modelos como los fabricados por Facit, Triumphator y Walther. Máquinas de aspecto parecidos fueron las Odhner y Brunsviga, entre otras. Aunque éstas funcionaban a manivela, hubo también versiones impulsadas por motor. La mayoría de estas máquinas usaban el mecanismo Odhner o variantes del mismo. La Olivetti Divisumma realizaba las cuatro operaciones aritméticas básicas y contaba con una impresora. Las máquinas de teclado completo, incluyendo las movidas a motor, también fueron usadas en Europa durante varias décadas. Algunas máquinas más raras contaban hasta con 20 columnas en sus teclados completos.\n" +
                    "\n" +
                    "El desarrollo de las calculadoras electrónicas\n" +
                    "Las primeras computadoras mainframe, usando inicialmente válvulas de vacío y luego transistores en sus circuitos lógicos, aparecieron a finales de los años 1940 y 1950. Esta tecnología supondría un obstáculo en el desarrollo de las calculadoras electrónicas.\n" +
                    "\n" +
                    "El desarrollo de los transistores, así como el trabajo del profesor Maximino Rodríguez Vidal en la Universidad de Cambridge, en su estudio “Diseño lógico de una máquina de calcular electrónica\"3\u200B4\u200B fueron capitales para la aparición de las primeras máquinas de calcular manejables.\n" +
                    "\n" +
                    "En 1954 IBM presentó en los Estados Unidos una gran calculadora fabricada con transistores y, en 1957, la compañía lanzó la primera calculadora «comercial» de este tipo, la IBM 608, que ocupaba varios armarios y costaba unos 80 000\$.5\u200B\n" +
                    "\n" +
                    "La Casio Computer Co., Ltd. de Japón lanzó el Modelo 14-A en 1957, considerada la primera calculadora «compacta» totalmente eléctrica del mundo. No usaba lógica electrónica, sino que se basaba en relés y era construida dentro de un escritorio.\n" +
                    "\n" +
                    "En octubre de 1961 se anunció la primera calculadora de escritorio totalmente electrónica del mundo, la Bell Punch/Sumlock Comptometer ANITA (A New Inspiration To Arithmetic/Accounting, ‘una nueva inspiración para la aritmética/contabilidad’).6\u200B7\u200B Esta máquina diseñada y construida en Gran Bretaña usaba tubos de vacío, tubos de cátodo frío y decatrones en su circuitería, y tenía doce tubos de cátodo frío de tipo Nixie para mostrar los resultados. Se presentaron dos modelos: el Mk VII para la Europa continental y el Mk VIII para Gran Bretaña y el resto del mundo, comercializados ambos a principios de 1962. El Mk VII era un diseño ligeramente anterior con un modo de multiplicación más complicado y pronto fue abandonado en favor de la versión más simple Mk VIII. La ANITA tenía un teclado completo, parecido a los comptómetros mecánicos de la época, una característica presente entre las calculadoras electrónicas sólo en este modelo y en el Sharp CS-10A posterior. Bell Punch había fabricado calculadoras mecánicas del tipo comptómetro bajo los nombres Plus y Sumlock, y se había dado cuenta a mediados de los años 1950 de que el futuro de las calculadoras estaba en la electrónica. Contrataron al joven graduado Norbert Kitz, que había trabajado en el pionero proyecto británico de computador Pilot ACE, para dirigir el desarrollo. La ANITA se vendió bien al ser la única calculadora de escritorio electrónica disponible, siendo además silenciosa y rápida.\n" +
                    "\n" +
                    "\n" +
                    "Friden Modelo 132 calculadora en la colección permanente del Museo de los Niños de Indianápolis\n" +
                    "La tecnología de tubos de la ANITA fue superada en junio de 1963 por el Friden EC-130 estadounidense, que tenía un diseño basado en transistores, capacidad para mostrar 13 dígitos en una pantalla CRT de 5 pulgadas e introdujo la notación polaca inversa en el mercado de las calculadoras por un precio de 2200\$, aproximadamente el triple del coste de una calculadora electromecánica de la época. Como Bell Punch, Friden era un fabricante de calculadoras mecánicas que había decidido que el futuro estaba en la electrónica. En 1964 se presentaron más calculadoras totalmente electrónicas: Sharp presentó la CS-10A, que pesaba 25 kg y costaba 500 000 yenes (unos 2500\$ de la época), y la italiana Industria Macchine Elettroniche presentó la IME 84, a la que podían conectársele varios teclados y pantallas extras, de forma que pudieran usarla varias personas (pero aparentemente no a la vez).\n" +
                    "\n" +
                    "A los anteriores siguió una serie de modelos de calculadoras electrónicas de estos y otros fabricantes, incluyendo Canon, Mathatronics, Olivetti, SCM (Smith-Corona-Marchant), Sony, Toshiba. y en enero de 1965 se lanzó al mercado la Loci-2 la primera calculadora programable de los laboratorios Wang. Las primeras calculadoras usaban cientos de transistores de germanio, debido a que eran más baratos que los de silicio, en múltiples placas de circuitos. Los tipos de pantallas usados eran CRT, tubos Nixie de cátodo frío y lámparas incandescentes. Para el almacenamiento solía emplearse la memoria de línea de retardo o la memoria de toros, si bien la Toshiba Toscal BC-1411 parece haber usado una forma primitiva de RAM dinámica construida a partir de componentes discretos. Ya entonces existía demanda de máquinas más pequeñas y de menor consumo eléctrico.\n" +
                    "\n" +
                    "La calculadora programable Monroe Epic salió al mercado en 1967. Compuesta por una unidad grande de escritorio con impresora y una torre lógica de suelo conectada a esta, era capaz de ser programada para realizar muchas funciones típicas de una computadora. Sin embargo, la única instrucción de flujo que tenía era un salto incondicional implícito (GOTO) al final de una pila de operación, devolviendo el programa a su instrucción inicial. Por ello, no era posible incluir ninguna lógica de salto condicional. En esta época, la ausencia de salto condicional se usaba a veces para distinguir una calculadora programable de un ordenador.\n" +
                    "\n" +
                    "1970 a mediados de los 1980\n" +
                    "Las calculadoras electrónicas de mediados de los años 1960 eran grandes y pesadas máquinas de escritorio debido al uso de cientos de transistores en varias placas de circuitos, con un elevado consumo eléctrico que exigía el uso de una alimentación alterna. Se hicieron grandes esfuerzos para reducir la lógica necesaria para una calculadora en cada vez menos circuitos integrados, siendo la electrónica de las calculadoras una de las líneas punteras en el desarrollo de los semiconductores. Los fabricantes estadounidenses de semiconductores lideraron el desarrollo mundial de ltos LSI, comprimiendo más y más funciones en un solo circuito integrado. Esto llevó a alianzas entre fabricantes de calculadoras japoneses y empresas de semiconductores estadounidenses: Canon Inc. con Texas Instruments, Sharp Corporation (llamada entonces Hayakawa Electric) con North-American Rockwell Microelectronics, Busicom con Mostek e Intel, y General Instrument con Sanyo.\n" +
                    "\n" +
                    "Calculadoras de bolsillo\n" +
                    "Para 1970 una calculadora podía fabricarse usando solo unos pocos chips de mínimo consumo, permitiendo que los modelos portátiles fuesen alimentados con baterías. Las primeras calculadoras electrónicas portátiles aparecieron en Japón en 1970 y pronto fueron comercializadas por todo el mundo. Entre estas estaban la Sanyo ICC-0081 Mini Calculator, la Canon Pocketronic y la Sharp QT-8B micro Compet. La Canon Pocketronic fue un desarrollo del proyecto Cal-Tech que había sido iniciado en Texas Instruments en 1965 como proyecto de investigación para fabricar una calculadora portátil. La Pocketronic no tenía una pantalla tradicional, sino que imprimía los resultados en un rollo de papel térmico. Como resultado del proyecto Cal-Tech Texas Instruments obtuvo patentes clave sobre las calculadoras portátiles.\n" +
                    "\n" +
                    "Sharp hizo grandes esfuerzos para reducir el tamaño y consumo, y en enero de 1971 presentó la Sharp EL-8, también comercializada como Facit 1111, que estaba muy cerca de ser una calculadora de bolsillo. Pesaba algo menos de medio kilo, tenía una pantalla fluorescente de vacío, baterías recargables de níquel cadmio y su precio de partida fue 395\$.\n" +
                    "\n" +
                    "Sin embargo, los esfuerzos en el desarrollo de los circuitos integrados culminaron con la introducción a principios de 1971 de la primera «calculadora en un chip», la MK6010 de Mostek,8\u200B seguida por Texas Instruments más tarde ese mismo año. Aunque estas primeras calculadoras de bolsillo eran muy caras, estos avances en la electrónica junto con los desarrollos en la tecnología de visualizadores (como el visualizador fluorescente de vacío, LED y LCD) llevaron a que en unos pocos años las calculadoras de bolsillo baratas fueran comercialmente viables.\n" +
                    "\n" +
                    "La primera calculadora electrónica auténticamente de bolsillo fue la Busicom LE-120A HANDY, comercializada a principios de 1971. Fabricada en Japón, fue también la primera en usar una pantalla LED, la primera en usar un único circuito integrado, el ya mencionado Mostek, y la primera en alimentarse con pilas desechables. Usando cuatro pilas de tamaño AA, la LE-120A medía 124×72×24 mm.\n" +
                    "\n" +
                    "Una de las primeras calculadoras de bajo coste fue la Sinclair Cambridge, lanzada en agosto de 1973. Salió a la venta por 29,95£ y 5£ menos en formato kit. Las calculadoras Sinclair tuvieron mucho éxito por ser mucho más baratas que las de la competencia, si bien su diseño tenía fallos y la precisión de algunas de sus funciones era cuestionable. Los modelos científicos programables eran particularmente pobres en este aspecto.\n" +
                    "\n" +
                    "Mientras todos los desarrollos que llevaron a las calculadoras de bolsillo se sucedían, Hewlett Packard había estado desarrollando su propio modelo. Lanzado a principios de 1972 fue, a diferencia de otras calculadoras de bolsillo con las cuatro funciones aritméticas entonces disponibles, la primera en contar con funciones «científicas» que podía reemplazar a la regla de cálculo. La HP-35 de 395\$, junto con los posteriores modelos de HP orientados a la ingeniería, usaba la notación polaca inversa o postfija. Un cálculo como «8 más 5» se realizaba pulsando «8», «Enter↑», «5» y «+», en lugar de, con la notación infija algebraica «8», «+», «5» y «=».\n" +
                    "\n" +
                    "La primera calculadora de bolsillo programable fue la HP-65, lanzada en 1974. Tenía capacidad para 100 instrucciones, pudiendo escribir y leer programas con un lector de tarjetas magnéticas incorporado. Un año después la HP-25C introdujo la «memoria continua», es decir, una memoria CMOS que retenía los programas y datos cuando la calculadora se apagaba. En 1979 HP lanzó la primera calculadora «alfanumérica» programable y ampliable, la HP-41C. Podía ampliarse con módulos RAM (memoria) y ROM (software), así como con periféricos como lectores de códigos de barras, microcasetes y unidades de disco flexible, impresora térmica de rollo y diversas interfaces de comunicación (RS-232, HP-IL, HP-IB).\n" +
                    "\n" +
                    "Las calculadoras mecánicas siguieron vendiéndose, si bien sus ventas decrecieron rápidamente, durante los primeros años 1970, y muchos de los famosos fabricantes cerraron o fueron adquiridos. Las calculadoras de tipo comptómetro fueron conservadas a menudo durante mucho tiempo por su conveniencia al sumar y listar, especialmente en la contabilidad, debido a que un operador debidamente experimentado podría introducir todos los dígitos de un número de un solo movimiento, más rápidamente que una calculadora «serie». Los comptómetros fueron sustituidos por la introducción de ordenadores más que de mejores calculadoras. En esta misma época también decayó el uso de las reglas de cálculo en favor de las calculadoras.\n" +
                    "\n" +
                    "Mejoras técnicas\n" +
                    "Durante los años 1970 la calculadora de bolsillo electrónica sufrió un rápido desarrollo. Las pantallas de LED rojos y de vacío fluorescente azul o verde consumían demasiada electricidad, haciendo que la calculadora tuviese poca autonomía (del orden de horas, siendo pues comunes las baterías recargables) o fuese lo suficientemente grandes como para aceptar baterías de gran tamaño y capacidad. A principios de la década las pantallas de cristal líquido (LCDs) estaban en su infancia y era objeto de mucha preocupación que tuvieran una vida operativa corta. Busicom fue una compañía muy innovadora, que cuando presentó el modelo LE-120A HANDY, la primera calculadora de bolsillo y la primera con pantalla LED, también anunció el modelo LC, con pantalla LCD. Sin embargo, hubo problemas con esta pantalla y la calculadora nunca salió a la venta. La primera calculadora con LCD viable fue fabricada por Rockwell International y comercializada desde 1972 por otras compañías bajo nombres como Dataking LC-800, Harden DT/12, Ibico 086, Lloyds 40, Lloyds 100, Prismatic 500 (o P500) y Rapid Data Rapidman 1208LC. Los primitivos LCDs de la época mostraban los números de color plateado contra un fondo oscuro. Para lograr un contraste alto estos modelos iluminaban la pantalla de cristal usando una lámpara incandescente o similar, lo que eliminaba los beneficios del bajo consumo del LCD. Estos modelos solo fueron vendidos durante uno o dos años.\n" +
                    "\n" +
                    "Una serie de calculadoras de mucho mayor éxito usando pantallas LCD reflexivas fue lanzada en 1972 por Sharp Corporation con su modelo EL-805, que era una calculadora de bolsillo delgada. Este y otros modelos similares usaban la tecnología COS (Crystal on Substrate) de Sharp, que empleaba una placa de circuito similar a un cristal que era también una parte integral del LCD. Al operar el usuario veía los números mostrados a través de esta placa. La tecnología COS debió resultar demasiado cara y solo fue usada en unos pocos modelos antes de que Sharp volviese a los circuitos convencionales, si bien todos los modelos con pantallas LCD reflexivas se denominan a menudo «COS».\n" +
                    "\n" +
                    "A mediados de los años 1970 aparecieron las primeras calculadoras con las actuales pantallas LCD «normales», con dígitos oscuros contra un fondo gris, si bien las primeras tenían a menudo un filtro amarillo sobre ellas para eliminar los dañinos rayos ultravioletas. La gran ventaja del LCD es que es pasivo y refleja la luz, lo que requiere mucha menos energía que generarla. Esto abrió el camino para las primeras calculadoras del tamaño de una tarjeta de crédito, como la Casio Mini Card LC-78 de 1978, que podía funcionar meses con un par de pilas de botón.\n" +
                    "\n" +
                    "También hubo un constante progreso en la electrónica interior de las calculadoras. Todas las funciones lógicas de una calculadora habían sido incluidas en un solo circuito integrado ya en 1971, pero entonces era tecnología punta, resultando los costes prohibitivos. Muchas calculadoras siguieron usando dos o más circuitos integrados, especialmente las científicas y programables, hasta finales de la década.\n" +
                    "\n" +
                    "El consumo energético de los circuitos integrados también fue reducido, especialmente con la introducción de la tecnología CMOS. Debutando en la Sharp \"EL-801\" de 1972, los transistores de las celdas lógicas de los chips CMOS solo consumían una energía apreciable cuando cambiaban de estado. Las pantallas LED y VFD había exigido a menudo transistores o circuitos adicionales, pero las pantallas LCD eran más fáciles de usar directamente desde los circuitos de la propia calculadora.\n" +
                    "\n" +
                    "Con este consumo de energía reducido se hizo posible el usar células solares como fuente de electricidad, lo que se logró sobre 1978 por calculadoras tales como la Royal Solar 1, Sharp EL-8026 y Teal Photon.\n" +
                    "\n" +
                    "Calculadoras de bolsillo para todo el mundo\n" +
                    "\n" +
                    "La Casio CM-602 Mini Electronic Calculator de los años 1970 realizaba las funciones básicas.\n" +
                    "Al principio de los años 1970 las calculadoras electrónicas de mano eran muy caras respecto al sueldo medio, resultando artículos de lujo. Este alto precio era debido a que su construcción necesitaba de varios componentes mecánicos y electrónicos caros de producir y relativamente escasos. Muchas compañías grandes y pequeñas previeron buenos beneficios en el negocio de las calculadoras, donde los márgenes eran altos. Sin embargo, el coste de las calculadoras cayó inexorablemente a medida que se abarataban sus componentes y las técnicas de producción involucradas, y el efecto de las economías de escalas se sintieron.\n" +
                    "\n" +
                    "Para 1976 el coste de las calculadoras de bolsillo más simples había caído a unos pocos dólares, una vigésima parte del de 5 años antes. Las consecuencias de esta caída fueron primero que las calculadoras de bolsillos eran asequibles para casi cualquiera, y luego que resultaba difícil para los fabricantes lograr beneficios, lo que llevó a que muchas compañías abandonaran el mercado o cerrasen. Las que sobrevivieron tendieron a ser las que lograban mayores ventas de calculadoras de mayor calidad o las que producían modelos científicos y programables de gama alta.\n" +
                    "\n" +
                    "De mediados de los años 1980 a la actualidad\n" +
                    "\n" +
                    "Calculadora programable HP49g+ de Hewlett-Packard.\n" +
                    "La primera calculadora capaz de realizar cálculos simbólicos fue la HP-28, lanzada en 1987. Era capaz, por ejemplo, de resolver simbólicamente ecuaciones cuadráticas. La primera calculadora gráfica fue la Casio fx7000G lanzada en 1985.\n" +
                    "\n" +
                    "Los dos principales fabricantes, HP y TI, lanzaron modelos con cada vez más características durante los años 1980 y 1990. A finales de siglo, la línea entre una calculadora gráfica y una PDA u ordenador portátil no estaba clara, pues muchas calculadoras avanzadas como la TI-89 y la HP-49G podían derivar e integrar funciones, correr procesadores de texto y software PIM, y conectar por cable o IR a otros equipos.\n" +
                    "\n" +
                    "En marzo de 2002 HP anunció que dejaba de fabricar calculadoras, lo que resultó difícil de aceptar por parte de algunos fanáticos de los productos de la compañía, teniendo en particular la gama HP-48 una base de clientes extremadamente fiel. HP reinició la producción de calculadoras a finales de 2003, si bien los nuevos modelos no tenían la calidad mecánica y el sobrio diseño de las anteriores calculadoras que una vez las hicieron famosas, pues la compañía decidió adoptar un estilo más «joven», como el de los modelos de su competidora TI. En los primeros días de las calculadoras, los vendedores de HP eran conocidos por empezar las demostraciones de sus productos tirando la calculadora al suelo, pero los actuales modelos se consideran aparatos baratos y desechables.\n" +
                    "\n" +
                    "Con la revolución de internet los usuarios han creado sus propias calculadoras, permitiendo que muchos programadores colaboren en todo el mundo para desarrollar completos sistemas de cálculo utilizando dispositivos de mano como PDA, Pocket PC y Nintendo DS.\n" +
                    "\n" +
                    "Actualmente, existen calculadoras «en línea» diseñadas para funcionar como las normales, pero que gracias a Internet permiten ciertos cálculos imposibles para las convencionales, como cambios de moneda, tipos de interés y estadísticas en tiempo real."

    }
}